// client/src/app/components/show-user-review/sticky-review-styles/tear-drop-elevated/tear-drop-elevated.component.ts
import {Component, Input, OnInit} from '@angular/core';
import * as moment from 'moment';
@Component({
    selector: 'app-tear-drop-elevated',
    templateUrl: './tear-drop-elevated.component.html',
    styleUrls: ['./tear-drop-elevated.component.scss']
})
export class TearDropElevatedComponent implements OnInit {
    @Input() reviewData?: any = ''; // default style is set to Rounded
    reviewByUser: string = '';
    constructor() { }

    ngOnInit() {
    }


    /**
     * Function to fetch count of review stars
     * @param rating
     */
    public getStars(rating) {
        const starts = new Array(1);
        for (let i = 1; i < rating; i++) {
            starts.push(i);
        }
        return starts;
    }

    /**
     * Method to format the time/date and show to the sticky reviews
     * @param created_at
     */
    public getReviewTimeFormated(reviewAt) {
        const reviewTime = moment.utc(reviewAt).local().format('YYYY-MM-DD HH:mm:ss');
        const currentTime = moment().format('YYYY-MM-DD HH:mm:ss');
        const timeDiffrence = moment(currentTime).diff(moment(reviewTime));
        return moment.duration(timeDiffrence).humanize();
    }

}

<!-- Tear drop elevated sticky review -->
<!-- Add pop_small class to popupparent elements OR popupParent's parent element when parent space is less than 320px -->
<div class="popupParent" [ngClass]="reviewData.type === 2 ? 'audioParent_5':''" *ngIf="reviewData.type !== 3">
    <div class="popupTxt popup_template_5" style="margin-bottom: 30px;">
        <div class="figPopup">
<!--          <figure [style.background-image]="'url(https://'+ reviewData.url_link +'/storage/images/'+ reviewData.image +')'" *ngIf="reviewData.image"></figure>-->
          <figure [style.background-image]="'url('+ reviewData.url_link +'images/'+ reviewData.image +')'" *ngIf="reviewData.image"></figure>
          <figure [style.background-image]="'url(../../../../assets/images/face_icon_small.png)'" *ngIf="!reviewData.image" class="defBg"></figure>
        </div>
        <div class="bodyPopup">
            <h6>{{reviewData.name}} </h6>
            <p *ngIf="reviewData.type === 1">{{reviewData.description}} </p>
            <!-- Audio Type review -->
            <div class="audioRv" *ngIf="reviewData.type === 2">
<!--                <audio src="https://{{reviewData.url_link}}/storage/audios/{{reviewData.description }}" controls controlslist="nodownload"></audio>-->
              <audio src="{{reviewData.url_link}}audios/{{reviewData.description }}" controls controlslist="nodownload"></audio>
            </div>
            <footer class="popupFt">
                <span class="timePop">{{getReviewTimeFormated(reviewData.created_at)}} ago</span>
                <span class="pwBy"><img src="../../../../../../assets/images/icon_poweredby.png" alt="">by</span>
                <span *ngIf="reviewData.has_brand === 1"> {{reviewData.brands.name  |  slice:0:10 }}</span>
                <span *ngIf="reviewData.review_link.campaign.branding === 1"> {{reviewData.review_link.campaign.branding_details.brand_name  |  slice:0:10 }}</span>
                <figure *ngFor="let rating of getStars(reviewData.rating)">
                    <img src="../../../../assets/images/small_star_active.png" alt="">
                </figure>
            </footer>
        </div>
        <a href="javascript:void(0)" class="closePopup"></a>
    </div>
</div>



<!-- video review -->

<div style="display: block;" class="popAdd vidPreV_parent" *ngIf="reviewData.type === 3">
    <div class="popupParent vidParent_5" >
        <div class="vidPop">
            <div class="animateVid">
                                <span class="keyF1">
                                  <img src="../../../../assets/images/video_thumbs.png" alt="">
                                </span>
                <span class="keyF2">
                                  <img src="../../../../assets/images/video_triangle.png" alt="">
                                </span>
                <span class="keyF3">
                                  <img src="../../../../assets/images/video_star_2.png" alt="">
                                </span>
                <span class="keyF4">
                                  <img src="../../../../assets/images/video_star_1.png" alt="">
                                </span>
                <span class="keyF5">
                                  <img src="../../../../assets/images/video_star_3.png" alt="">
                                </span>
                <span class="keyF6">
                                  <img src="../../../../assets/images/video_star_4.png" alt="">
                                </span>
            </div>
            <div class="vidContain">
                <!-- video player will go here -->
                <video controlslist="nodownload" disablepictureinpicture width="320" height="240" controls>
<!--                    <source src="https://{{reviewData.url_link}}/storage/videos/{{reviewData.description}}" type="video/mp4">-->
                  <source src="{{reviewData.vid_link}}videos/{{reviewData.description}}" type="video/mp4">
                </video>
            </div>
        </div>
        <div class="popupTxt popup_template_5">
            <div class="figPopup">
<!--              <figure [style.background-image]="'url(https://'+ reviewData.url_link +'/storage/images/'+ reviewData.image +')'" *ngIf="reviewData.image"></figure>-->
              <figure [style.background-image]="'url('+ reviewData.url_link +'images/'+ reviewData.image +')'" *ngIf="reviewData.image"></figure>
              <figure [style.background-image]="'url(../../../../assets/images/face_icon_small.png)'" *ngIf="!reviewData.image" class="defBg"></figure>
            </div>
            <div class="bodyPopup">
                <h6>{{reviewData.name}} </h6>
                <footer class="popupFt">
                    {{getReviewTimeFormated(reviewData.created_at)}} ago
                    <span><img src="../../../../assets/images/icon_poweredby.png" alt=""></span>
                    by
                    <span *ngIf="reviewData.has_brand === 1"> {{reviewData.brands.name  |  slice:0:10 }}</span>
                    <span *ngIf="reviewData.review_link.campaign.branding === 1"> {{reviewData.review_link.campaign.branding_details.brand_name  |  slice:0:10 }}</span>
                    <figure *ngFor="let rating of getStars(reviewData.rating)">
                        <img src="../../../../assets/images/small_star_active.png" alt="">
                    </figure>
                </footer>
            </div>
            <a href="javascript:void(0)" class="closePopup"></a>
        </div>
    </div>
</div>

// widget/src/components/Widgets/TearDropElevated.vue
<template>
  <div>
    <!-- tear drop widget for text review start -->
    <div class="popupParent" v-if="data.type === 1 && !timeOut">
      <div class="popupTxt popup_template_5">
        <div class="figPopup">
          <figure v-if="data.image_url" v-bind:style="{ backgroundImage: 'url('+data.image_url+')'}"></figure>
          <figure v-else style="background-image:url(../../assets/images/dp.jpeg);"></figure>
        </div>
        <div class="bodyPopup">
          <h6>{{data.name}}</h6>
          <p>{{data.review}}</p>

          <footer class="popupFt">
            <span class="timePop">{{ getReviewTimeFormated(data.reviewed_at) + ' ago' }}</span>
            <span class="pwBy" v-if="isBranded"><img src="../../assets/images/icon_poweredby-white.png" alt="">by</span>
            <a :href="data.has_brand ? data.brands.url : brandingData.url" target="_blank" v-if="isBranded">{{data.has_brand ? data.brands.name : brandingData.name}}</a>

            <figure class="rateStar" v-for="(item, index) in 5" :key="index">
              <i :class="index+1 <= data.rating ? 'star': 'star inactive'">
                &#9734;
              </i>
            </figure>
          </footer>
        </div>
        <a class="closePopup" aria-label="Close Popup" @click="stopIteration"></a>
      </div>
    </div>
    <!-- tear drop widget for text review end -->

    <!-- tear drop widget for audio review start -->
    <div class="popupParent audioParent_5" v-if="data.type === 2 && !timeOut">
      <div class="popupTxt popup_template_5">
        <div class="figPopup">
          <figure v-if="data.image_url" v-bind:style="{ backgroundImage: 'url('+data.image_url+')'}"></figure>
          <figure v-else style="background-image:url(../../assets/images/dp.jpeg);"></figure>
        </div>
        <div class="bodyPopup">
          <h6>{{data.name}}</h6>
          <div class="audioRv">
            <AudioPlayer :audio-list="audioSource"
                        :show-play-button="true"
                        :show-prev-button="false"
                        :show-next-button="false"
                        @play="onPlayerPlay($event)"
                        @pause="onPlayerPause($event)">
            </AudioPlayer>
          </div>

          <footer class="popupFt">
            <span class="timePop">{{ getReviewTimeFormated(data.reviewed_at)+ ' ago' }}</span>
            <span class="pwBy" v-if="isBranded"><img src="../../assets/images/icon_poweredby-white.png" alt="">by</span>
            <a :href="data.has_brand ? data.brands.url : brandingData.url" target="_blank" v-if="isBranded">{{data.has_brand ? data.brands.name : brandingData.name}}</a>

            <figure class="rateStar" v-for="(item, index) in 5" :key="index">
              <i :class="index+1 <= data.rating ? 'star': 'star inactive'">
                &#9734;
              </i>
            </figure>
          </footer>
        </div>
        <a class="closePopup" aria-label="Close Popup" @click="stopIteration"></a>
      </div>
    </div>
    <!-- tear drop widget for audio review end -->

    <!-- tear drop widget for video review start -->
    <div class="popupParent vidParent_5" v-if="data.type === 3 && !timeOut">
      <div class="vidPop">
        <div class="animateVid">
          <span class="keyF1">

          </span>
          <span class="keyF2">

          </span>
          <span class="keyF3">

          </span>
          <span class="keyF4">

          </span>
          <span class="keyF5">

          </span>
          <span class="keyF6">

          </span>
        </div>
        <div class="vidContain">
          <video-player class="vjs-default-skin"
              ref="videoPlayer"
              :options="videoPlayerOptions"
              :playsinline="true"
              @play="onPlayerPlay($event)"
              @pause="onPlayerPause($event)"></video-player>
        </div>
      </div>
      <div class="popupTxt popup_template_5">
        <div class="figPopup">
          <figure v-if="data.image_url" v-bind:style="{ backgroundImage: 'url('+data.image_url+')'}"></figure>
          <figure v-else style="background-image:url(../../assets/images/dp.jpeg);"></figure>
        </div>
        <div class="bodyPopup">
          <h6>{{data.name}}</h6>

          <footer class="popupFt">
            <span class="timePop">{{ getReviewTimeFormated(data.reviewed_at)+ ' ago' }}</span>
            <span class="pwBy" v-if="isBranded"><img src="../../assets/images/icon_poweredby-white.png" alt="">by</span>
            <a :href="data.has_brand ? data.brands.url : brandingData.url" target="_blank" v-if="isBranded">{{data.has_brand ? data.brands.name : brandingData.name}}</a>

            <figure class="rateStar" v-for="(item, index) in 5" :key="index">
              <i :class="index+1 <= data.rating ? 'star': 'star inactive'">
                &#9734;
              </i>
            </figure>
          </footer>
        </div>
        <a class="closePopup" aria-label="Close Popup" @click="stopIteration"></a>
      </div>
    </div>
    <!-- tear drop widget for video review end -->
  </div>

</template>

<script>
import '../../assets/css/popup.css'
// require styles
import 'video.js/dist/video-js.css'
import '../../assets/css/video-custom-theme.css'
import '@liripeng/vue-audio-player/lib/vue-audio-player.css'

import Vue from 'vue'
import VueMoment from 'vue-moment'
import moment from 'moment-timezone'
import { videoPlayer } from 'vue-video-player'
import { AudioPlayer } from '@liripeng/vue-audio-player'

Vue.use(VueMoment, {
  moment
})

export default {
  props: {
    data: {},
    counter: {
      type: Number,
      default: 0
    },
    isBranded: {},
    brandingData: {},
    timeOut: {
      type: Boolean,
      default: false
    },
    ongoingInterval: {}
  },
  name: 'teardropelevated',
  data: function () {
    return {
      componentName: 'Im teardrop elevated component',
      videoPlayerOptions: {},
      audioSource: []
    }
  },
  computed: {
  },
  components: {
    videoPlayer: videoPlayer,
    AudioPlayer: AudioPlayer
  },
  methods: {
    stopIteration () {
      window.clearInterval(this.ongoingInterval)
      this.$emit('iterationStopped', true)
    },
    // listen event
    onPlayerPlay(player) {
      window.clearInterval(this.ongoingInterval)
      this.$emit('iterationPaused', true)
    },
    onPlayerPause(player) {
      this.$emit('startIteration', true)
    },
    getReviewTimeFormated(reviewAt) {
      const reviewTime = moment.utc(reviewAt).local().format('YYYY-MM-DD HH:mm:ss');
      const currentTime = moment().format('YYYY-MM-DD HH:mm:ss');
      const timeDiffrence = moment(currentTime).diff(moment(reviewTime));
      return moment.duration(timeDiffrence).humanize();
    }
  },
  beforeUpdate () {
    let vm = this
    this.audioSource = []
    this.audioSource.push(this.data.review)
    this.videoPlayerOptions = {
      // videojs options
      muted: true,
      language: 'en',
      sources: [{
        src: vm.data.review
      }],
      fluid: false
    }
  },
  mounted () {
    let vm = this
    this.audioSource = []
    this.audioSource.push(this.data.review)
    this.videoPlayerOptions = {
      // videojs options
      muted: true,
      language: 'en',
      sources: [{
        src: vm.data.review
      }],
      fluid: false
    }
  }
}
</script>
